---
# See https://docs.github.com/rest/releases/releases#get-the-latest-release
- block:
  - name: Determine latest GitHub release (local)
    delegate_to: localhost
    become: false
    uri:
      url: "https://api.github.com/repos/ncabatoff/process-exporter/releases/latest"
      body_format: json
      headers:
        X-GitHub-Api-Version: "2022-11-28"
    register: _github_release
    until: _github_release.status == 200
    retries: 5

  - name: Set slm_monitoring_proc_exp_version
    set_fact:
      # remove the v from version tag
      slm_monitoring_proc_exp_version: "{{ _github_release.json.tag_name | regex_replace('^v?(.*)$', '\\1')}}"
  when: (slm_monitoring_proc_exp_version == 'latest')
  run_once: true

- name: Create cache directory
  file:
    path: /var/cache/process_exporter/{{ slm_monitoring_proc_exp_version }}
    state: directory

- name: Download process-exporter ({{ ansible_architecture }})
  get_url:
    dest: /var/cache/process_exporter/{{ slm_monitoring_proc_exp_version }}
    url: https://github.com/ncabatoff/process-exporter/releases/download/v{{ slm_monitoring_proc_exp_version }}/process-exporter-{{ slm_monitoring_proc_exp_version }}.linux-{{ slm_monitoring_go_architecture[ansible_architecture] }}.tar.gz
    checksum: sha256:https://github.com/ncabatoff/process-exporter/releases/download/v{{ slm_monitoring_proc_exp_version }}/checksums.txt

- name: Extract process-exporter archive
  unarchive:
    src: /var/cache/process_exporter/{{ slm_monitoring_proc_exp_version }}/process-exporter-{{ slm_monitoring_proc_exp_version }}.linux-{{ slm_monitoring_go_architecture[ansible_architecture] }}.tar.gz
    dest: /var/cache/process_exporter/{{ slm_monitoring_proc_exp_version }}
    remote_src: yes

- name: Copy process-exporter {{ slm_monitoring_proc_exp_install_location }}
  copy:
    src: /var/cache/process_exporter/{{ slm_monitoring_proc_exp_version }}/process-exporter-{{ slm_monitoring_proc_exp_version }}.linux-{{ slm_monitoring_go_architecture[ansible_architecture] }}/process-exporter
    dest: "{{ slm_monitoring_proc_exp_install_location }}"
    mode: u=rwx,g=rx,o=rx
    remote_src: true

- name: Create user for process-exporter
  user:
    create_home: false
    name: "{{ slm_monitoring_proc_exp_user }}"
    system: true
    state: present

- name: Create config directory for process-exporter
  file:
    state: directory
    path: "{{ slm_monitoring_proc_exp_config_path | dirname }}"
    owner: "{{ slm_monitoring_proc_exp_user }}"

- name: Create config file for process-exporter
  copy:
  # TODO: fix template evaluation
    content: "{{ slm_monitoring_proc_exp_config }}"
    dest: "{{ slm_monitoring_proc_exp_config_path }}"
    owner: "{{ slm_monitoring_proc_exp_user }}"
  notify:
    - Restart process-exporter service

- name: Place system service for process-exporter
  template:
    src: process-exporter.service.j2
    dest: /etc/systemd/system/process-exporter.service
  notify:
    - Reload system service configuration
    - Restart process-exporter service