---
- name: Stop process-exporter service
  ansible.builtin.systemd_service:
    name: process-exporter
    state: stopped

- name: Remove files
  ansible.builtin.file:
    path: "{{item}}"
    state: absent
  loop:
    - /etc/systemd/system/process-exporter.service
    - /var/cache/process_exporter
    - "{{ slm_monitoring_proc_exp_config_path | dirname }}"
  notify:
    - Reload system service configuration

- name: Remove user for process-exporter
  user:
    name: "{{slm_monitoring_proc_exp_user}}"
    state: absent
  when: slm_monitoring_proc_exp_user != 'root'