---
- name: Reload system service configuration
  systemd_service:
    daemon_reload: true

- name: Restart cAdvisor service
  systemd_service:
    name: cadvisor
    enabled: true
    state: restarted

- name: Restart process-exporter service
  systemd_service:
    name: process-exporter
    enabled: true
    state: restarted
