---
- name: Reload system service configuration
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart cAdvisor service
  ansible.builtin.systemd:
    name: cadvisor
    enabled: true
    state: restarted

- name: Restart process-exporter service
  ansible.builtin.systemd:
    name: process-exporter
    enabled: true
    state: restarted
